export const SET_REARRANGE_SECTIONS             = 'SET_REARRANGE_SECTIONS';
export const SET_GROUP_POSITION_SECTION         = 'SET_GROUP_POSITION_SECTION';
export const TOGGLE_REARRANGE_SECTIONS_TOOLBOX  = 'TOGGLE_REARRANGE_SECTIONS_TOOLBOX';
export const SET_YOUR_CV_SKILLS                 = 'SET_YOUR_CV_SKILLS';
export const SET_YOUR_CV_QUALIFICATIONS         = 'SET_YOUR_CV_QUALIFICATIONS';
