export const SET_REARRANGE_SECTIONS             = 'SET_REARRANGE_SECTIONS';
export const SET_GROUP_POSITION_SECTION         = 'SET_GROUP_POSITION_SECTION';
export const TOGGLE_REARRANGE_SECTIONS_TOOLBOX     = 'TOGGLE_REARRANGE_SECTIONS_TOOLBOX';
